export enum screenNavigators {
  APP_NAVIGATOR = 'APP_NAVIGATOR',
  BOTTOM_TABS_NAVIGATOR = 'BOTTOM_TABS_NAVIGATOR',
  AUTH_NAVIGATOR = 'AUTH_NAVIGATOR',
  REGISTRATION_NAVIGATOR = 'REGISTRATION_NAVIGATOR',
  RECOVERY_NAVIGATOR = 'RECOVERY_NAVIGATOR',
  SUCCESS_CHANGE_NAVIGATOR = 'SUCCESS_CHANGE_NAVIGATOR',
  PROFILE_EDIT_NAVIGATOR = 'PROFILE_EDIT_NAVIGATOR',
  ACTIVE_POLL_NAVIGATOR = 'ACTIVE_POLL_NAVIGATOR',
}
export enum screenNames {
  LOGIN = 'LOGIN',
  REGISTRATION = 'REGISTRATION',
  PROFILE = 'PROFILE',
  NEWS = 'NEWS',
  ABOUT = 'ABOUT',
  PROFILE_EDIT = 'PROFILE_EDIT',
  RESET_PASSWORD = 'RESET_PASSWORD',
  USER_SETTINGS = 'USER_SETTINGS',
  TABS = 'TABS',
  MY_DAY = 'MY_DAY',
  DETAILS = 'DETAILS'
}
